import { Inter } from "next/font/google";
import "./globals.css";
import Menu from './menu';
import Burger from './burger_menu';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Api from './api';
import ProfileClient from "./userData/userProfile";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ArenaBet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="relative min-h-screen  items-center justify-center overflow-hidden bg-black text-white m-10">
          <Menu />
         <Api/>
          {children}

          {/* Spotlights */}
          
            <div 
              className=" w-96 h-96 rounded-full fixed top-0 left-0"
              style={{
                background: 'radial-gradient(circle, rgba(255,0,150,0.5) 0%, rgba(255,0,150,0) 80%)'
              }}
            ></div>
            <div 
              className="w-96 h-96 rounded-full  fixed top-[50%] left-[50%]"
              style={{
                background: 'radial-gradient(circle, rgba(0,204,255,0.5) 0%, rgba(0,204,255,0) 76%)'
              }}
            ></div>
         
        </body>
      </UserProvider>
    </html>
  );
}
