import { Inter } from "next/font/google";
import "./globals.css";
import Menu from './menu'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import ProfileClient from "./userData/userProfile";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <UserProvider>
	<body className={inter.className}>
		<Menu></Menu>
		{children}</body>
    </UserProvider>
    </html>
  );
}
