import { Inter } from "next/font/google";
import "./globals.css";
import Menu from './menu'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import SetTransaction from "./transaction/setTransaction";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const RootLayout = ({ children }) => {
	return (
	  <html lang="en">
		<UserProvider>
		  <body>
			<Menu />
			<SetTransaction />
			{children}
		  </body>
		</UserProvider>
	  </html>
	);
  };

  export default RootLayout;